### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by pan90** [Cocolennon/TopLuck#2] opened 2024-04-01 09:24 UTC
It looks like there are some issues with this plugin

exception stack:
```
[17:17:50 ERROR]: Could not pass event BlockBreakEvent to TopLuck v1.1.0
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "data" is null
	at me.cocolennon.topluck.util.PlayerData.addPlayerData(PlayerData.java:96) ~[TopLuck-1.1.0.jar:?]
	at me.cocolennon.topluck.listeners.PlayerBrokeBlock.onBlockBroken(PlayerBrokeBlock.java:28) ~[TopLuck-1.1.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor61.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:git-Luminol-"5e79b7c"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[luminol-1.20.4.jar:git-Luminol-"5e79b7c"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[luminol-1.20.4.jar:git-Luminol-"5e79b7c"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:375) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:334) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:298) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1903) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:102) ~[?:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[luminol-1.20.4.jar:git-Luminol-"5e79b7c"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[luminol-1.20.4.jar:git-Luminol-"5e79b7c"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[luminol-1.20.4.jar:git-Luminol-"5e79b7c"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"5e79b7c"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"5e79b7c"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

```

I am using luminol 1.20.4.
[https://github.com/LuminolMC/Luminol](https://github.com/LuminolMC/Luminol)

**Comment by pan90** [comment] 2024-04-01 09:26
There doesn't seem to be good compatibility with Folia?

**Comment by pan90** [comment] 2024-04-01 09:27
Once the player breaks the block, the console displays this exception message

**Comment by Cocolennon** [comment] 2024-04-02 01:48
> There doesn't seem to be good compatibility with Folia?

This error is not related to Folia. The plugin works as intended and the error is from an error in the code.

**Comment by Cocolennon** [comment] 2024-04-02 01:49
Fixed in latest commit, releasing the update right now

**Comment by Cocolennon** [comment] 2024-04-02 01:50
PS: I advise using official versions of Folia as it is the only version I and many other plugin devs base ourselves when testing.

**Closed as completed by Cocolennon** 2024-04-02 01:49 UTC
